be_questions = [
    "When the admission process for Degree Engineering is likely to start?",
    "Why has the admission process not started?",
    "Will there be any PIN distribution this time like previous?",
    "How to pay registration fees?",
    "What are the registration charges?",
    "Do I need to register differently for different courses?",
    "What documents are needed to register or create profile?",
    "What documents do I need for Degree Engineering?",
    "What documents do I need for Diploma to Degree Engineering/Pharmacy?",
    "What documents do I need for Degree Architecture?",
    "What documents do I need for MBA/MCA",
    "What documents do I need for Master of Engineering",
    "What documents do I need for Master of Pharmacy",
    "What are the fees to be paid for registration at the cyber space centres?",
    "Can I do online registration from home?",
    "I am unable to register online, can I do it manually?",
    "How can I edit registration details before and after confirming?",
    "If the income certificate is in the name of mother, will it be valid?",
    "From whom can I get certificate of caste?",
    "From whom can I get certificate of income?",
    "From whom can I get certificate of physically handicapped?",
    "From whom can I get certificate of In-service men?",
    "From whom can I get certificate of ex-service men?",
    "What should I do if the name in School LC and caste certificate/income certificate is not matching?",
    "I have registered in open category and now I have the certificate for Caste/Income/PH/ESM. How can I change category?",
    "Can I avail the benefits of reservation if I am from DAMAN & DIU/DNH ?",
    "If I have appeared in JEE(Main) and GUJCET both, can I apply in both together?",
    "For Degree Engineering and Degree/Diploma Pharmacy, if I have studied outside Gujarat, what is the procedure for admission through ACPC?",
    "If I have studied outside Gujarat, can I avail benefit of reservation or chances to include in the online process of Government seats?",
    "What is the level of disability for availing seats under PH (Physically Handicapped) quota?",
    "If both parents are not alive, then who can act as a guardian for caste and income certificate?",
    "If a student is applying for TFWS, is he considered for that particular category?",
    "What are the criteria for eligibility for admission through ACPC for Degree Engineering course?",
    "What are the criteria for eligibility for admission through ACPC for Degree/Diploma Pharmacy course?",
    "How are merit marks calculated for GSEB/CBSE/ICSE/NIOS for Degree Engineering admissions?",
    "How can I check my merit rank?",
    "Where can I get information about the various colleges and branches coming under ACPC?",
    "How much choices one candidate can fill?",
    "If a candidate wants to go for reshuffling, does he need to report at the admitted institute?",
    "If a candidate wants to go for reshuffling, does he need to pay the fees at the admitted institute?",
    "If I get admission of choice in the mock round, can I secure it?",
    "If a SC/ST/SEBC candidate gets admission under the open category, will he be eligible for a scholarship from the government?",
    "What is the procedure for admission for NRI/NRI sponsor candidate?",
    "How can I update my result if there is a change after rechecking?",
    "Where is the information for the fee structure of self-finance institutes?",
    "After allotment, in how many days do we have to report at the admitted institute?",
    "Is there any reservation or special quota for girls?",
    "How and when do I get information for the availability of vacant seats in various institutes?",
    "How can I check where else could I have got admission?",
    "What is the procedure for admission in Management Quota?",
    "If I opt for management quota admission, am I still eligible for admission in regular quota?",
    "If I get admission in management quota, can I go for reshuffling?",
    "How to confirm my allotted seat?",
]

be_answers = [
    "The process of registration for Degree Engineering is expected to start at the end of June.",
    "The examination of CBSE, ICSE, JEE(Main), and GUJCET are pending, but students can register prior to the same.",
    "No, due to the current COVID-19 situation, the entire admission process will be online.",
    "After registration, candidates need to pay registration fees ONLINE through Credit Card/Net Banking/UPI interfaces.",
    "Degree Engineering-350, Degree Pharmacy-350, Diploma Pharmacy-350, Diploma to Degree Engineering-350, Diploma to Degree Pharmacy-350, MBA-500, MCA-500, Master of Engineering-500, Master of Pharmacy-500, Degree Architecture-350.",
    "No, only a single registration is required.",
    "Passport size photograph, Birth Date proof, School Leaving Certificate, Aadhar Card, HSC Marksheet, Valid Income Certificate, Valid Caste Certificate, Valid In-service men category, Valid Ex-servicemen category.",
    "Latest HSC mark sheet, GUJCET scorecard, JEE(Main) NEET scorecard.",
    "Provisional Eligibility Certificate of Diploma course, Grade History.",
    "Latest HSC Mark Sheet, Valid NATA-2023 Scorecard.",
    "Valid CMAT 2023 Scorecard, Grade History of Bachelor Course, Provisional Eligibility Certificate of undergraduate course.",
    "Valid GATE Scorecard, Grade History of Bachelor Course, Provisional Eligibility Certificate of undergraduate course, Passport size Photograph, Sponsorship documents.",
    "Valid GPAT Scorecard, Grade History of Bachelor Course, Provisional Eligibility Certificate of undergraduate course, Passport size Photograph, Sponsorship documents.",
    "No fees are required to pay.",
    "Yes.",
    "No, only online registration within the time limit specified by ACPC.",
    "Before confirming, you can edit online, and after confirming, you have to request ACPC through mail to edit.",
    "In case of death of father, it is valid; otherwise, not valid.",
    "District Collector, Deputy Collector, Assistant Collector, Social Welfare Officer/District Development Officer/Dy. District Development Officer/Taluka Development Officer, Mamlatdar.",
    "District Collector, Deputy Collector, Assistant Collector, Prant Officer, Mamlatdar, DDO, TDO.",
    "Government Medical officer countersign by Civil surgeon.",
    "Commanding officer of the unit where serving.",
    "Director, Sainik Welfare Board, Gujarat State, or the District Sainik Welfare Officer.",
    "You should get the income certificate corrected from the issuing authority.",
    "Reach any Help Centre with original as well as a photocopy of the certificate within the stipulated time limit stipulated by ACPC.",
    "Yes, if you are a Domicile of Gujarat.",
    "The admission process for JEE(Main) and GUJCET is separate. Please check the guidelines provided by ACPC.",
    "You are eligible for 5%\ of seats in Government and Grant-in-Aid institutions.",
    "No, but for exceptional cases, read rule 5(3) notification of the Education Department of the Government of Gujarat for Bachelor of Engineering and Technology.",
    "Not less than 40%.",
    "The Legal guardian can act as a guardian.",
    "Yes, subject to a valid income certificate issued by the competent authority.",
    "Passed HSCE in Science Stream with 45% marks for Open category in theory only or theory and practical with Physics and Mathematics as compulsory subjects along with Chemistry/Biology/Bio-Technology or Technical Vocational as a Subject in the qualifying examination.",
    "Passed HSCE in Science Stream with Physics and Chemistry as compulsory subjects along with Mathematics/Biology/Bio-Technology or Technical Vocational as a Subject in the qualifying examination.",
    "The merit marks for GSEB/CBSE/ICSE/NIOS for Degree Engineering admissions are calculated as the sum of sixty percentage of the percentile obtained in the theory subjects Physics, Chemistry, and Mathematics, and forty percentage weightage of the percentile obtained in the GUJCET.",
    "Candidates can verify their rank by logging in to their module at the NIC website. The same will be reflected in registration details, and candidates can also check the allotted rank on www.acpc-gujarat.gov.in.",
    "Check the Information Booklet provided with PIN and from the websites www.jacpcldce.in and www.gujacpc.nic.in.",
    "Candidates can fill all the choices of their liking.",
    "No.",
    "No, candidates only have to pay after the online admission process.",
    "No.",
    "Yes, the student will get a scholarship if eligible.",
    "Follow guidelines by ACPC on www.jacpcldce.ac.in.",
    "Submit a photocopy of the mark sheet from the concerned board of the rechecking result at ACPC immediately within one week.",
    "Refer Fee Regulatory Committee website www.frctech.ac.in.",
    "Under 3 working days.",
    "No.",
    "After allotment of the seat at each round and on the website www.jacpcldce.ac.in.",
    "From the cut-off marks details on the website after each round of seat allotment.",
    "As per the guidelines given by ACPC available on the website www.jacpcldce.ac.in.",
    "Yes.",
    "Yes.",
    "Candidates can verify the allotment status in the result section.",
]
# List of Pharmacy Questions
pharmacy_questions = [
    "Can candidates from out of Gujarat get the benefits of category reservation?",
    "How can I get updates regarding the admission process?",
    "Is PGCET compulsory?",
    "Is there any separate hall ticket for candidates?",
    "Helpline number for the admission?",
    "What documents are required or necessary or needed during the online registration process?",
    "Can I write the CGPA in place of percentage in the column % marks obtained?",
    "If I apply now and I do not secure minimum marks, will the registration fee be returned?",
    "Is choice filling necessary?",
    "I am getting a list of only a few programs in choice filling, what should I do?",
    "What is Auto-Locking?",
    "How many choices of courses can I apply to during the choice filling process?",
    "What if I have lost my GPAT scorecard?",
    "What to do if I have not received my GPAT scorecard?",
    "Is GPAT qualified candidate eligible for scholarship?",
    "Can I accept the first round allotted seat later?",
    "What preparation is needed or required to fill the choices?",
    "Why do I see those choices for which vacancies are not available on the website?",
    "Can I modify the choices after locking?",
    "Am I required to pay seat acceptance fee again if my seat is upgraded in the next round?",
    "Can I apply as a GPAT qualified candidate if not qualified or did not appear in GPAT?",
    "How can I pay the registration fee or seat confirmation fee?",
    "Can I participate in seat allotment in further rounds without accepting the seat?",
    "What is the best strategy for choice filling?",
    "Is financial aid available for Master of Pharmacy students?",
    "Are there specific timelines for Master of Pharmacy program applications?"
]

# List of Pharmacy Answers
pharmacy_answers = [
    "Only if he is having a valid category certificate issued by the authorities empowered by the Govt. of Gujarat.",
    "The candidates are advised to visit the admission committee websites and log-in to the online admission portal regarding various announcements, verification process, and other guidelines on a daily basis.",
    "Only for Non-GPAT candidates including sponsored (Non-GPAT) have to appear in PGCET for the corresponding admission year to become eligible for admission.",
    "No separate call letter will be issued for appearing in PGCET.",
    "Helpline number: 079-26566000",
    "Candidates are required to upload the colored scanned copy of the original Documents listed in “Rule 17 of admission rules notified by the Government of Gujarat” available under the Rules tab of the committee’s website.",
    "No. The CGPA or percentage (%) of marks awarded by the respective university or institute must be filled in as Percentage marks only.",
    "No. The Registration fee is non-refundable If secure minimum marks are not scored as specified in the rules also candidature will not be considered for the further admission process.",
    "Yes, it is necessary. If no choice is filled in, no seat will be allotted. There is only automatic locking and not automatic choice filling.",
    "Outstate candidates other than Gujarat can see only the Govt/GIA seats during choice filling.",
    "While filling the choices if you forget to lock, your last saved choices will get automatically locked on the last day of choice filling as per the schedule.",
    "There is no limit on the number of choices from the list of eligible Institutions and programs.",
    "Pease contact the GPAT office to obtain a scorecard.",
    "Please contact the GPAT office to obtain a scorecard.",
    "Only the admitting institute can award the MHRD Post Graduate scholarship to those candidates who have secured marks equal to or more than the “qualifying marks” in GPAT and for the corresponding category of the candidate with due validity of the GPAT qualification as per the provisions of prevailing guidelines. Also, candidates must note that mere admission as “GPAT qualified candidates” does not guarantee MHRD Scholarship/Assistantship.",
    "No, if you do not accept the seat in the respective seat acceptance period of the round by online seat confirmation and paying seat confirmation token fee, you will lose your allotted seat.",
    "It is particularly important to study the courses available in all the participating institutes. One may visit their official websites or contact the helpline of that participating institute to know more.",
    "They are shown as all the choices which are shown based on your eligibility, including those on which the seat may not be available at the beginning but may become available due to the upgrading of other candidates.",
    "Yes. The candidate can modify choices using the Choice Unlocking option available in the candidate's login.",
    "No. There is no need to pay Seat Acceptance Fee again. However, the balance seat acceptance fee shall have to be paid if any.",
    "No. Since, for GPAT qualified candidates, possessing a valid GPAT score is essential.",
    "Only ONLINE payment through UPI/ Debit Card/Credit Card/ Net Banking is available.",
    "Yes, but the same institute and same course seat will not be allotted to you in all subsequent rounds of the admission process.",
    "Each choice of institute or branch must be such that you know completely what you are asking for. Include only those choices in your list where you are prepared to join in case of an allotment. Fill choices as per your preference of the courses that you would like to join. Choice filling may not be done considering which course you can be allotted based on your rank. One must refrain from a take-a-chance approach.",
    "Yes, many Government schemes and universities or institutions offer financial aid options, such as scholarships, MHRD assistantships for GPAT qualified candidates, and loans. It's recommended to explore the financial aid opportunities provided by the specific university/institution and various government schemes applicable.",
    "Yes, the admission process comprises various admission-related activities such as the registration process, document verification, appearance in CET (PGCET), merit declaration, choice filling, allotment of admission, etc. The detailed schedule is available on the admission committee website."
]
march_mplan_questions = [
    "What is the procedure for M.Arch/M.Plan Admission?",
    "Which are the Websites for admission of M.Arch/M.Plan courses?",
    "How the Merit list is prepared?",
    "What is the eligibility for M.Arch admission?",
    "What is the eligibility for M.Plan admission?",
    "Who can apply for the admission registration process of M.Arch/M.Plan?",
    "What is the registration fee for M.Arch/M.Plan admission?",
    "Are all the seats of Self-financed Institutes in Gujarat State filled by the ACPC?",
    "How can I know the updates regarding the admission process?",
    "For whom PGCET is compulsory?",
    "Is any separate hall ticket issued for candidates?",
    "Where can candidates get all the updates of the admission process?",
    "Is any Helpline number for the admission?",
    "If I apply now and I do not secure minimum marks, will the registration fee be returned?",
    "Are there specific timelines for M.Arch/M.Plan?",
    "What is the Admission Procedure for M.Arch/M.Plan?",
]

march_mplan_answers = [
    "The Admission process is carried out by Admission Committee for Professional Courses (ACPC) as per rules defined by the Education department of the Government of Gujarat.",
    "http:/jacpcldce.ac.in or https://acpc.gujarat.gov.in",
    "Marks secured in the Common entrance test (PGCET) conducted by ACPC in the concerned admission year.",
    "The candidate shall have passed Bachelor of Architecture with a minimum of 50% (45%\ for SC/ST/SEBC/EWS candidates) at the qualifying exam from a recognized university/institution. The candidate shall have to appear in the Common Entrance test (PGCET) conducted by the ACPC in the concerned admission year.",
    "The candidate shall have passed Bachelor of Architecture OR B.E./B. Tech. (Civil Engineering) OR Bachelor of Planning OR Post Graduation in Geography or Economics or Sociology or an equivalent qualification with a minimum of 50% (45%\ for SC/ST/SEBC/EWS candidates) at the qualifying exam from a recognized university/institution. The candidate shall have to appear in the Common Entrance test (PGCET) conducted by the ACPC in the concerned admission year.",
    "For M.Arch, the candidate shall have passed Bachelor of Architecture, and for M.Plan, the candidate shall have passed Bachelor of Architecture OR B.E./B. Tech. (Civil Engineering) OR Bachelor of Planning OR Post Graduation in Geography or Economics or Sociology or an equivalent qualification with a minimum of 50% marks (45%\ for SC/ST/SEBC/EWS candidates) at the qualifying exam. Candidates waiting for final semester results or backlog result can also apply but have to pass the qualifying examination as per the Admission rules. However, the merit number in such cases will be given if the mark sheet and provisional degree certificate of passing the qualifying exam are uploaded within the scheduled time limit.",
    "INR 1000/- (Non-refundable) through D. D. In favour of “GTERS - ACPC Income (Fees)”, Payable at Ahmedabad for the year 2023-24.",
    "For the admission to the first year of M.Arch/M.Plan in Government, Grant-in-aid and Self-financed Institutes in Gujarat State, on State Quota of all institutions and voluntarily surrendered Management quota seats by self-financed institutes, the Government of Gujarat conducts a web-based offline admission process for the relevant academic year.",
    "The candidates should visit the admission committee websites, regarding various announcements and other guidelines on a day-to-day basis.",
    "All candidates, including sponsored, shall have to appear in PGCET for the corresponding admission year to become eligible for admission.",
    "No separate call letter will be issued for appearing in PGCET.",
    "Visit the website https://jacpcldce.ac.in and https://acpc.gujarat.gov.in time to time.",
    "Helpline number: 079-26566000.",
    "No. The Registration fee is non-refundable if minimum marks are not scored as specified in the rules also candidature will not be considered for the further admission process.",
    "Yes, the admission process has various admission-related activities such as the registration process, appearance in CET (PGCET), merit declaration, allotment of admission, etc.",
    "Application Form with the list of documents to be attached and general instruction, Key dates for the admission process, Seat matrix are uploaded on the ACPC website http://jacpcldce.ac.in or http://acpc.gujarat.gov.in Based on marks obtained by eligible candidate appeared in PGCET examination conducted by ACPC in corresponding year a Merit list is prepared and declared on ACPC website as well as Offline counselling is done at ACPC, Ahmedabad as per the merit list and choices of candidates.",
]
mtech_questions = [
    "What is the procedure for ME/MTech Admission?",
    "Which are the Websites for admission of ME/MTech courses?",
    "How the Merit list is prepared?",
    "Does the candidate have to verify their documents in person?",
    "What is the eligibility for ME/MTech admission?",
    "Who can apply for the admission registration process of ME/MTech?",
    "What is the registration fee for ME/MTech admission?",
    "How can candidates know that their registration form is successfully verified?",
    "Are all the seats of Self-financed Institutes in Gujarat State filled by the ACPC?",
    "Is any arrangement for the candidates who are not having any internet facility to carry out the online registration process?",
    "Is it compulsory to register online even for GATE qualified candidates?",
    "What is the criteria for out-state candidates?",
    "Is out-state candidates can avail the benefits of category reservation?",
    "How can I know the updates regarding the admission process?",
    "For whom PGCET is compulsory?",
    "Is any separate hall ticket issued for candidates?",
    "Where can candidates get all the updates of the admission process?",
    "Is any Helpline number for the admission?",
    "What documents are needed during the online registration process?",
    "Can I mention the CGPA in place of percentage in the column % marks obtained?",
    "If I apply now and I do not secure minimum marks, will the registration fee be returned?",
    "Whether choice filling is necessary?",
    "When I proceed to the choice filling, I am getting a list of only a few programs, what should I do?",
    "What is Auto-Locking?",
    "How many choices of courses/specializations can I apply to during the choice filling process?",
    "What if I have not received my GATE scorecard? Or I have lost my GATE scorecard?",
    "Is a GATE qualified candidate eligible for a scholarship?",
    "I have been offered a seat in the 1st round of allotment. I will not be able to accept the seat at this moment. Can I accept the same seat later?",
    "What preparations I have to do to fill choices?",
    "I have not done class XII; instead, I have done a 3-year diploma course. What document should I upload for the class XII mark sheet?",
    "While filling choices, why do I see even those choices for which vacancies are not available as shown on the website?",
    "Can the candidate modify the choices after locking?",
    "Am I required to pay seat acceptance fee again if my seat is upgraded based on my consent and choice filling in the next round?",
    "If I have not qualified in GATE or I do not have a valid GATE score or I did not appear in GATE; Can I apply as a GATE qualified candidate?",
    "How can I pay the registration fee/Seat confirmation fee? Shall I pay by cash or cheque?",
    "I am not interested in the seat offered in a particular round. Can I participate in seat allotment in further rounds without accepting the seat now?",
    "What is the best strategy for choice filling?",
    "Is financial aid available for Master of Engineering/Technology students?",
    "Are there specific timelines for Master of Engineering/Technology program applications?",
    "Can I apply to multiple disciplines of Master of Engineering/Technology programs simultaneously?",
    "Can I apply if I have failed in some subjects?",
]

mtech_answers = [
    "The Admission process is carried out by the Admission Committee for Professional Courses (ACPC), as per rules notified by the Education department, Government of Gujarat.",
    "https://gujacpc.admissions.nic.in, http:/jacpcldce.ac.in OR https://acpc.gujarat.gov.in",
    "Valid GATE Score for GATE Qualified candidates, Marks in the Common entrance test (PGCET) in the admission year.",
    "No, the entire process of admission is online.",
    "BE/BTech with a minimum of 50% (45%\ for SC/ST/SEBC/EWS candidates) from a recognized university/institution. The candidate should have a qualified valid GATE score in a relevant discipline for GATE qualified candidates and appearance in PGCET for Non-GATE students.",
    "Candidates who have passed BE/BTech with a minimum of 50% marks (45%\ for SC/ST/SEBC/EWS candidates).",
    "INR 1000/- (Non-refundable) per discipline applied for.",
    "If any discrepancy is found, a query will be generated and sent to the candidate's registered Mobile & Email. Every candidate is informed to check his Login frequently on https://gujacpc.admissions.nic.in.",
    "For the admission to the first year of Master of Engineering/Technology (ME/MTech.) in Government, Grant-in-aid and Self-financed Institutes in Gujarat State, on State Quota of all institutions and voluntarily surrendered Management quota seats by self-financed institutes, the Government of Gujarat conducts a web-based online admission process for the relevant academic year.",
    "The aspiring candidate not having an internet facility can avail the same at Cyber Space Centers designated by the admission committee without paying any charges. (The list is available on the committee's website. The working hours of designated Cyber Centers are from 11:00 AM to 5:00 PM except Public Holidays.",
    "All GATE qualified candidates, Non-GATE candidates, and all sponsored candidates shall have to register online to become eligible for further admission process. Please note that no other means of registration is available.",
    "5%\ seats are available for eligible candidates from outstate (out of Gujarat) in Government/Grant-in-Aid (GIA) institutes.",
    "Only if he is having a valid category certificate issued by the authorities empowered by the Govt. of Gujarat.",
    "The candidates are advised to visit the admission committee websites and log-in to the online admission portal using their User ID and password regarding various announcements, verification process, and other guidelines on a day-to-day basis.",
    "All Non-GATE candidates, including sponsored (Non-GATE), shall have to appear in PGCET for the corresponding admission year to become eligible for admission. However, GATE qualified candidates have not to appear in PGCET.",
    "No separate call letter will be issued for appearing in PGCET.",
    "All are available on the website https://jacpcldce.ac.in and https://acpc.gujarat.gov.in. All the aspiring candidates, their parents, and well-wishers are advised to check the websites of ACPC from time to time for all the latest information and updates on the admission process.",
    "Helpline number: 079-26566000.",
    "Candidates are required to upload the colored scanned copy of the original Documents listed in “Rule 17 of admission rules notified by the Government of Gujarat”. The notification is available under the Rules tab of the committee's website.",
    "No, The CGPA or percentage (%) of marks awarded by the respective university or institute must be filled in as Percentage % marks only after conversion as per the concerned university's resolution.",
    "No, The Registration fee is non-refundable.",
    "Yes, If no choice is filled in, no seat will be allotted.",
    "The list of available programs for a candidate depends on her/his eligibility under qualifying degree so, while selecting the qualifying degree from the dropdown menu, please go through all the available options before selecting the exact one.",
    "In case you forgot to lock, your last saved choices will get automatically locked on the last day of choice filling as per the schedule.",
    "You are free to opt for as many choices as you wish to choose from the list of eligible Institutions and programs.",
    "Please contact the GATE office to obtain a scorecard as it will be compulsorily required to be uploaded for document verification during the registration process.",
    "It is the responsibility of the admitting institute/university to award the MHRD/AICTE Post Graduate scholarship/assistantship to only those candidates who have secured marks equal to or more than the “qualifying marks” in the concerned GATE exam.",
    "No, if you do not accept the seat in the respective seat acceptance period of the round by online seat confirmation and paying seat confirmation token fee, you will not only lose your allotted seat but also the same institute and the same course seat will not be allotted to you in all subsequent rounds of admission.",
    "One may visit official websites or contact the helpline of that participating institute to know offered courses. Please ensure that you fulfill all eligibility criteria, for all the choices you have filled.",
    "The candidate is required to upload the Diploma certificate of his/her 3-year diploma course in place of the 12th mark sheet.",
    "While filling your choices, you need to consider all the choices which are shown based on your eligibility, including those choices on which a seat may not be available at the beginning of the concerned round but may become available due to the up-gradation of other candidates.",
    "Yes, The candidate can modify choices using Choice Unlocking option available in the candidate's login.",
    "No, There is no need to pay Seat Acceptance Fee again but the balance seat acceptance fee shall have to be paid, if any.",
    "No, Since, for GATE qualified candidates, possessing a valid GATE score of the year 2021, 2022, and/or 2023 is essential.",
    "Only ONLINE payment through UPI/ Debit Card/Credit Card/ Net Banking is available. The Registration fee is a one-time payment and is non-refundable.",
    "Yes, but the same institute and the same course seat will not be allotted to you in all subsequent rounds of the admission process.",
    "Each choice of institute or branch must be such that you know completely what you are asking for. Include only those choices in your list where you are prepared to join in case of an allotment. As a general guide, you must fill choices as per your preference for the courses that you would like to join. Choice filling may not be done considering which course you can be allotted based on your rank. One must refrain from a take-a-chance approach. It should not happen that after getting an allotment you say, 'Oh! I did not want it.' If that is so, it should not have been in the list of choices.",
    "Many Government schemes and universities/institutions offer financial aid options, such as scholarships, MHRD-AICTE assistantships for GATE qualified candidates, and loans. It's recommended to explore the financial aid opportunities provided by the specific university/institution and various government schemes you're interested in.",
    "Yes, the detailed activity-wise schedule is available on the admission committee website. It's crucial to complete each activity before the stated deadline.",
    "Yes, you can apply to multiple disciplines of ME/MTech programs simultaneously, but the registration fee shall be Rs. 1000 per discipline applied for each discipline.",
    "The candidates whose final semester results or result of any backlog in the previous semester are awaited can also apply, but they shall have to pass the qualifying examination as mentioned in the Admission rules. The merit number in such cases will be allotted if the mark sheet and provisional degree certificate of passing the qualifying exam are furnished/uploaded within the scheduled time limit.",
]
mba_mca_questions = [
    "When will the MBA-MCA admission process start?",
    "What are the new changes in MBA-MCA admissions for the year 2023-24?",
    "Will there be any registration fee this time like last year?",
    "Do I need to register for MBA and MCA courses differently?",
    "Which documents are needed to register or create a profile?",
    "Do I need to visit a Help Center for document verification if I register for MBA/MCA admission?",
    "What are the fees to be paid for registration at the cyber space centers?",
    "Can I do online registration at home?",
    "I am unable to register online, can I do it manually?",
    "How can I edit registration details before and after confirmation?",
    "If the income certificate is in the name of the mother, will it be valid?",
    "Where can I get the format for certification for Physically Handicapped caste/non-creamy layer/income/Ex or In servicemen?",
    "What should I do if the name on the School L.C. and caste certificate/income certificate differs?",
    "How can I change the category?",
    "Is a candidate who completes graduation and HSC from outside Gujarat eligible for MBA-MCA admission?",
    "What is the level of disability required for availing seats under the PH (Physically Handicapped) quota?",
    "If both parents are not alive, then who can act as a guardian for caste and income certificates?",
    "What are the eligibility criteria for admission through ACPC for MBA/MCA Courses?",
    "How is the eligibility percentage calculated for MBA/MCA?",
    "How are merit marks calculated for MBA/MCA?",
    "If a student is applying for TFWS, is he considered for that particular category?",
    "What is the eligibility for TFWS?",
    "How can a candidate apply for admission on the TFW seat?",
    "How do I get admission on the TFW seat?",
    "Can a candidate change the filled choices?",
    "If filled choices are not locked, is it safe to logout?",
    "How many times can choices be edited?",
    "If I get admission of choice in the mock round, can I secure it?",
    "If the seats in the reserved quota are full, can a candidate from SC/ST/SEBC/EWS/PH/ESM get admission in the open category?",
    "Are original documents to be submitted for MBA/MCA?",
    "If a SC/ST/SEBC candidate gets admission under the open category, will he be eligible for a scholarship from the Government?",
    "What is the procedure for admission for MQ/NRI/NRI sponsored candidates?",
    "What are the documents required for admission for MQ/NRI/NRI sponsored candidates?",
    "To how many colleges can I apply for management quota?",
    "If I opt for management quota admission, am I still eligible for admission in the regular quota?",
    "If I get admission in the management quota, can I take part in the online admission process of ACPC?",
    "Where is the information available regarding the fee structure of self-finance institutes?",
    "In reshuffling, if a candidate gets admission in a Government institute from SFI, when will he get a refund?",
    "If I have already paid the fees for admission in the first round, do I have to pay the fees for subsequent rounds?",
    "Is there any reservation or special quota for girls in MBA/MCA?",
    "If I have registered for both MBA & MCA courses, is it the same merit number given for both courses?",
    "How can I check where I have got admission?",
]

mba_mca_answers = [
    "The registration process for MBA-MCA will start soon. Keep checking the website: http://www.jacpcldce.ac.in or https://acpc.gujarat.gov.in for updates and registration details.",
    "- The entire process is online; no need to submit documents physically. - Registration fees: Rs. 500/- for MBA/MCA and Rs. 750/- for MBC (for both MBA & MCA courses). - 50%\ of the total intake in SFI institute is considered as management quota. It may be surrendered to ACPC for admission as per notification. Final management quota admission is decided by the respective institute.",
    "The entire admission process will be online, and you don't need a PIN for registration. After registration, pay the fees online:\n- MBA: Rs. 500/-\n- MCA: Rs. 500/-\n- MBA and MCA Courses (MBC): Rs. 750/-",
    "Yes, you need to register separately:\n- MBA: Register for MBA\n- MCA: Register for MCA\n- Both MBA and MCA courses: Register for MBC.",
    "Prepare these documents (in electronic form/scan/.pdf) for smooth registration:\n- Passport size photograph (100 kb or lower) in .jpeg format.\n- Birth date proof, school leaving certificate, or Aadhar card (200 kb or lower) in .pdf format.\n- Scan copy of HSC mark-sheet in .pdf format.\n- Scan copy of original final semester mark sheet showing your percentage marks or CGPA.\n- Valid CMAT 2023 scorecard in .pdf format.\n- Scan copy of valid caste certificate (SC/ST/EWS) if applicable, in .pdf format.\n- Scan copy of valid Non-Creamy Layer Certificate for SEBC in Gujarati if applicable, in .pdf format.\n- Scan copy of valid in-serviceman or ex-serviceman category certificate if applicable, in .pdf format.",
    "No, there are no help centers for document verification. The entire process is online, and no physical documents are required to be submitted.",
    "The designated cyber space centers offer online registration facilitation for free. There are no separate fees for registration at these centers.",
    "Yes, you can do online registration from anywhere with internet access.",
    "No, online registration is mandatory within the specified time limit as mentioned on the websites https://gujacpc.admissions.nic.in or https://gujacpc.nic.in.",
    "Before confirming registration, you can edit details online. After confirmation and fee payment, edits are not allowed. You can respond to queries via email or SMS.",
    "If your father is alive, an income certificate in the name of the mother is not valid. However, if the father has passed away, the income certificate in the name of the mother is valid. In such a case, you must upload both the scan copy of the death certificate of your father and the income certificate of your mother combined in one file in .pdf format.",
    "The following authorities are designated by the State Government for issuing these certificates:\n- Caste Certificate (SC/ST/SEBC/EWS): District Collector, Deputy Collector, Assistant Collector, Social Welfare Officer/District Development Officer/Dy. District Development Officer/Taluka Development Officer, Mamlatdar (Government of Gujarat officers).\n- Income Certificate: District Collector, Deputy Collector, Assistant Collector, Prant Officer, Mamlatdar/D.D.O./T.D.O. (Government of Gujarat officers).\n- Physically Handicapped Certificate: Government Medical officer countersigned by Civil surgeon.\n- In-Servicemen: Commanding officer of the unit where serving.\n- Ex-Servicemen: Director, Sainik Welfare Board, Gujarat State, or the District Sainik Welfare Officer.\n- Non-Creamy Layer Certificate: District Collector, Deputy Collector, Assistant Collector, Prant Officer, Mamlatdar/D.D.O./T.D.O. (Government of Gujarat officers).",
    "You should get the income certificate corrected from the issuing authority immediately.",
    "You can change the category before confirming your registration if you have valid proof. After confirmation, you cannot change it.",
    "Yes, 5%\ of the seats are available for candidates from outside Gujarat in Government and Grant-in-aid colleges. A separate merit list will be prepared for such candidates based on CMAT-2023 scores.",
    "The disability should not be less than 40%.",
    "A legal guardian can act as a guardian for caste and income certificates. If there is no legal guardian, the candidate will be considered an orphan, and in such cases, no income certificate is required, but an orphan certificate issued by a competent authority is necessary.",
    "- Minimum Qualification: The candidate should have appeared in CMAT-2023 examination conducted by NTA (prescribed by AICTE) and should have passed the qualifying examination with a minimum of 50% (45%\ for reserved categories) for MBA and MCA courses. - For MBA: The candidate should have passed a Bachelor's Degree of minimum 3 years duration from recognized institutes/universities. - For MCA: The candidate should have passed the qualifying examination of B.C.A. / B.Sc. (Computer Science) / B.Sc. (IT) / B.E. (CSE) / B.Tech. (CSE) / B.E. (IT) / B.Tech. (IT) or equivalent Degree or any graduation degree with Mathematics, Business Mathematics, or Statistics at 10+2 level or Graduation level. For students with no Mathematics background, a compulsory bridge course will be framed by the respective University/Institution.",
    "For eligibility, 50% marks (45% marks for reserved categories) shall be computed based on the percentage of marks awarded for the qualifying degree by the institution/university. In case of grade points, the candidate must produce an equivalence percentage certificate from the University.",
    "Merit marks are calculated based on the CMAT 2023 scores for candidates who have passed the qualifying examination from any of the mentioned Universities/Institutes.",
    "Yes, the student is considered for TFWS category subject to having a valid income certificate issued by a competent authority.",
    "The family income should not exceed 8 Lakh per annum. Any category student can apply under this scheme.",
    "a) While registering for the first time, the candidate has to select 'yes' for applying under the TFW category.\nb) The candidate will be shown the TFW seat as one of the choices along with normal seats while filling choices online if they elected 'yes' in part (a). The candidate has to select both the TFW seat and the normal seat for admission to a particular institute/university.",
    "Upon filling the choice for the TFW seat, admission will be given purely based on merit.",
    "Yes, the candidate can edit the filled choices within the stipulated time decided by ACPC.",
    "There is no need to lock the filled choices until you complete your choice filling. However, during choice filling, you must save before logging out.",
    "Choices can be edited an unlimited number of times within the stipulated time decided by ACPC.",
    "No, the mock round is for practice purposes only and does not guarantee admission.",
    "This situation does not arise because category candidates are allotted first in open category seats. If no seat is available in the open category, only then are reserved category seats allotted.",
    "No, you are not required to submit any original documents anywhere.",
    "Yes, if the candidate meets the other requirements for eligibility for a scholarship.",
    "Please refer to the MBA/MCA notifications available on the website http://www.jacpcldce.ac.in or https://acpc.gujarat.gov.in for details regarding the admission procedure for MQ/NRI/NRI sponsored candidates.",
    "Please refer to the MBA/MCA notifications available on the website http://www.jacpcldce.ac.in or https://acpc.gujarat.gov.in for details regarding the required documents for admission for MQ/NRI/NRI sponsored candidates.",
    "You can find seat details from our website http://www.jacpcldce.ac.in or https://acpc.gujarat.gov.in.",
    "Yes, you are still eligible for admission in the regular quota.",
    "Yes, you can participate in the online admission process even if you get admission in the management quota.",
    "You can refer to the Fee Regulatory Committee website www.frctech.ac.in or check the institute details on the website: http://www.jacpcldce.ac.in or https://acpc.gujarat.gov.in.",
    "The refund will be given after the completion of the admission process as per the refund rule.",
    "Yes, you need to pay the fees as printed on the Bank Challan auto-generated after the second round.",
    "No, there is no specific reservation or special quota for girls in MBA/MCA.",
    "No, separate merit numbers will be generated based on your merit marks for MBA and MCA courses.",
    "You can log in to your account on https://gujacpc.admissions.nic.in or https://gujacpc.nic.in with your login ID and password and refer to the 'result' tab to check your admission status.",
]

greet_questions =[]
greet_answers =[]
